name: Release Pipeline

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v1.2.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21' 
        distribution: 'temurin'

    - name: Set up sbt
      uses: coursier/setup-action@v1
      with:
        apps: sbt

    - name: Build the project and generate the .jar
      run: |
        sbt clean compile package  

    - name: Get the tag version
      id: get_version
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

    - name: List target directory
      run: |
        ls -l target/scala-* 

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/scala-*/SoftwareEngineeringJJ-${{ env.VERSION }}.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

